### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Wionsito** [ComplementaryDevelopment/ComplementaryReimagined#40]
The game crashes when applying the shader.
I'm using macOS and Apple Silicon processor (M2), Iris 1.6.5 and Sodium 0.5.0
Version 2.2.1 works perfectly, but version 2.3 doesn't.
I think it's a compatibility issue because moving all the mods to another folder (except sodium and iris) works
but I have more than 200 mods, so it would take me a lot of time to find the problem, if there's a known incompatible mod or a possible one, please let me know.
This is the log in case that helps:

java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createVertexShader(IrisChunkProgramOverrides.java:58)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:143)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:237)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:266)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$edj000$iris$begin(ShaderChunkRenderer.java:562)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:43)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:328)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:226)
	at net.minecraft.class_761.method_3251(class_761.java:20514)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:450)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1033)
	at net.minecraft.class_761.handler$doj000$iris$renderTerrainShadows(class_761.java:10537)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createVertexShader(IrisChunkProgramOverrides.java:58)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:143)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:237)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:266)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$edi000$iris$begin(ShaderChunkRenderer.java:562)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:43)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:328)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:226)
	at net.minecraft.class_761.method_3251(class_761.java:20514)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:450)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1033)
	at net.minecraft.class_761.handler$doi000$iris$renderTerrainShadows(class_761.java:10537)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

**Comment by Wionsito** [comment]
I got it working right know by moving resource packs, if it continues working i will close this issue

**Comment by Wionsito** [comment]
I disabled the mod ¨Chunks Fade In¨ and it worked, re-enabled the mod again and crashed again, ¨Chunks Fade In¨ is the incompatible mod.

**Comment by EminGT** [comment]
Thank you for the detailed report. This information may be useful in the future
